language: cpp
sudo: required
dist: bionic

cache:
  apt:
    packages:
       - libboost-all-dev
       - libompl-dev
       - libeigen3-dev

env:
  - GLS_TREAT_WARNINGS_AS_ERRORS=ON

matrix:
  include:
    - os: linux
      compiler: gcc
      env: SUDO=sudo BUILD_TYPE=Debug COMPILER=GCC
    - os: linux
      compiler: gcc
      env: SUDO=sudo BUILD_TYPE=Release COMPILER=GCC

install:

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGLS_TREAT_WARNINGS_AS_ERRORS=$GLS_TREAT_WARNINGS_AS_ERRORS ..
  - make -j4 all
  - make -j4 test
  - sudo make install

after_success:

after_failure: 
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log

notifications:
  email: false
