language: cpp
sudo: required
dist: bionixc

cache:
  apt: true

env:
  - GLS_TREAT_WARNINGS_AS_ERRORS=ON

matrix:
  include:
    - os: linux
      compiler: gcc
      env: SUDO=sudo BUILD_TYPE=Debug COMPILER=GCC
    - os: linux
      compiler: gcc
      env: SUDO=sudo BUILD_TYPE=Release COMPILER=GCC

install:
  - .ci/install.sh;

script:
  - .ci/script.sh;

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure: 
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log

notifications:
  email: false
